In [1]:
import numpy as np

In [17]:
values = [90, 86, 72]
array = np.array(values)
size = array.size
print("count:", size)

count: 3


In [18]:
total = array.sum()
print("total:", total)

total: 248


In [19]:
mean = array.mean().round()
print("mean:", mean)

mean: 83.0


In [20]:
range_arr1 = np.arange(10)
print(range_arr1)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
range_arr2 = np.arange(0, 1, 0.2)
print(range_arr2)

[0.  0.2 0.4 0.6 0.8]


In [22]:
numbers = np.array([1, 2, 3, 4, 5])
numbers += 2
print(numbers)

[3 4 5 6 7]


In [23]:
numbers = np.array([1, 2, 3, 4, 5])
numbers *= 2
print(numbers)

[ 2  4  6  8 10]
