In [2]:
import numpy as np

In [3]:
range_arr1 = np.arange(10)
print(range_arr1)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
range_arr2 = np.arange(0, 1, 0.2)
print(range_arr2)

[0.  0.2 0.4 0.6 0.8]


In [22]:
numbers = np.array([1, 2, 3, 4, 5])
numbers += 2
print(numbers)

[3 4 5 6 7]


In [23]:
numbers = np.array([1, 2, 3, 4, 5])
numbers *= 2
print(numbers)

[ 2  4  6  8 10]


In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 足し算
result = arr1 + arr2
print(result)

# 掛け算
result = arr1 * arr2
print(result)

[5 7 9]
[ 4 10 18]


In [25]:
zeros = np.zeros((5), dtype=int)
print(zeros)

zeros = np.zeros((2, 3))
print(zeros)

complex_array = np.zeros((2, 3), dtype=complex)
print(complex_array)

[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [32]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("array1")
print(arr1)
print("array2")
print(arr2)

array1
[[1 2 3]
 [4 5 6]]
array2
[[ 7  8  9]
 [10 11 12]]


In [27]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
print(arr3[2][0])

7


In [11]:
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [30]:
print(arr4[0][3])

7
